name: practice/test
run-name: practice/test
on:
  workflow_dispatch:
    inputs:
      StackName:
        type: choice
        description: Practice StackName
        options:
          - pr1-staging-stack
          - pr1-staging stack-2
          - pr1-staging-backup

jobs:
  setup-job-environment:
    runs-on: ubuntu-latest
    steps:
      - name: run test workflow
        id: test-step
        run: |
          echo "Hello worlds"
          echo "my_output=Hello, World!" >> $GITHUB_OUTPUT
        
      - name: write the value of set variable
        run: |
          echo "${{ steps.test-step.outputs.my_output }}"
      
